<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x86;x64;ARM64</Platforms>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <PublishAot>true</PublishAot>
    <Nullable>enable</Nullable>
    <ApplicationIcon>..\ChordLaunchpad\Assets\AppIcon.ico</ApplicationIcon>
    <Version>2026.9.0.1</Version>
    <AssemblyVersion>2026.9.0.1</AssemblyVersion>
    <FileVersion>2026.9.0.1</FileVersion>
    <Product>ChordLaunchpad</Product>
    <Description>ChordLaunchpad Launcher</Description>
  </PropertyGroup>
</Project>
